/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        // Primeira casa do args irá vim uma matriz gerada pelo exercicio anterior.
        String[][] matriz = new String[9][9];
        if (args.length > 0){
            for (int y = 0; y < matriz.length; y ++){
                for (int x = 0; x < matriz.length; x ++){
                    matriz[y][x] = String.valueOf(args[0].charAt(x));
                }
            }
            imprime(matriz);
        }else {
            System.out.println("Erro ao inserir a matriz!");
        }

    }

    private static void imprime (String[][] matriz){
        for (int y = 0; y < matriz.length; y ++){
            for (int x = 0; x < matriz.length; x ++){
                System.out.print(matriz[y][x]);
            }
            System.out.println();
        }
    }
}
