/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.time.LocalDate;
import java.util.HashMap;
import java.util.Scanner;

public class App {
    private Scanner leitor = new Scanner(System.in);
    private HashMap<String, Livro> livros = new HashMap<>();

    public static void main(String[] args) {
        App app = new App();

    }

    private void cadastrar(){
        System.out.println("Qual é o ISBN do livro?");
        String isbn = leitor.nextLine();
        while (this.livros.containsKey(isbn)){
            System.out.println("Já tem um livro com esse ISBN, informe novamente!");
            isbn = leitor.nextLine();
        }
        System.out.println("Qual é o titulo do livro?");
        String titulo = leitor.nextLine();
        System.out.println("Qual é o nome do Autor do livro?");
        String autor = leitor.nextLine();
        System.out.println("Em que ano o livro foi lançado?");
        int ano = leitor.nextInt();
        Livro livro = new Livro(isbn, titulo, autor, ano);

        leitor.close();
        this.livros.put(isbn, livro);
    }

    private void listar(){
        this.livros.forEach((chave, valor) -> {
            System.out.println("ISBN: " + chave + " - Titulo: " + valor.getTitulo());
        });
    }

    private void consultarPorISBN(){
        System.out.println("Qual é o ISBN do livro que deseja consultar?");
        String isbn = leitor.nextLine();
        if(!this.livros.containsKey(isbn)){
            System.out.println("Esse ISBN não existe!");
        }
        System.out.println(this.livros.get(isbn).toString());
    }

    private void consultarPorAutor(){
        System.out.println("Qual é o Autor do livro que deseja consultar?");
        String autor = leitor.nextLine();
        if(!this.livros.containsValue(autor)){
            System.out.println("Esse Autor não existe!");
        }
        this.livros.forEach((chave, valor) -> {
            if(valor.getAutor().equals(autor)){
                System.out.println("ISBN: " + chave + " - Titulo: " + valor.getTitulo());
            }
        });
        leitor.close();
    }

    private void consultarPorAno(){
        System.out.println("Qual é o Ano do livro que deseja consultar?");
        int ano = leitor.nextInt();
        if(!this.livros.containsValue(ano)){
            System.out.println("Não existe nenhum livro cadastrado com esse ano!");
        }
        this.livros.forEach((chave, valor) -> {
            if(valor.getAnoPublicacao() == ano){
                System.out.println("ISBN: " + chave + " - Titulo: " + valor.getTitulo());
            }
        });
        leitor.close();
    }

    private void atualizar(){
        System.out.println("Qual é o ISBN do livro que deseja atualizar?");
        String isbn = leitor.nextLine();
        Livro livro = this.livros.get(isbn);
        if(livro == null){
            System.out.println("Esse ISBN não existe!");
        }
        System.out.println(livro.toString() + "\nQual informação deseja alterar? Caso não queira mudar um campo, Aperte ENTER!");
        String titulo = this.leitor.nextLine();
        if(!titulo.isEmpty()){
            livro.setTitulo(titulo);
        }
        String autor = this.leitor.nextLine();
        if(!autor.isEmpty()){
            livro.setAutor(autor);
        }
        String ano = this.leitor.nextLine();
        if(!ano.isEmpty()){
            int anoInteiro = Integer.parseInt(ano);
            livro.setAnoPublicacao(anoInteiro);
        }
        System.out.println("Livro atualizado!\n" + livro.toString());
    }

    private void remover(){
        System.out.println("Qual é o ISBN do livro que deseja remover?");
        String isbn = leitor.nextLine();
        if(this.livros.containsKey(isbn)){
        }
    }

}
