/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {
        ArrayList<Pessoa> pessoas = new ArrayList<>();

        pessoas.add(new Pessoa("Luciano Simas Junior", "luciano.sj@aluno.ifsc.edu.br"));
        pessoas.add(new Pessoa("Pedro Gonçalves", "pedro.gl@aluno.ifsc.edu.br"));
        pessoas.add(new Pessoa("Lionel Messi", "messi@aluno.ifsc.edu.br"));
        pessoas.add(new Pessoa("Luciano Simas Junior", "luciano.sj@aluno.ifsc.edu.br"));
        pessoas.add(new Pessoa("Juca", "juca@example.com"));
        pessoas.add(new Pessoa("Juca", "juca@example.com"));
        pessoas.add(new Pessoa("Juca", "juca@example.com"));

        System.out.println("Listagem das Pessoas Salvas no ArrayList");
        for(Pessoa pessoa : pessoas){
            System.out.println(pessoa.toString());
        }

        pessoas.removeIf(pessoa -> pessoa.getNome().equals("Juca"));

        System.out.println("Listagem das Pessoas Salvas no ArrayList com Lambda");
        pessoas.forEach(x -> System.out.println(x.getNome()));

        // Forma de listar mais enxuta, mas não permite acessar atributos do objeto a ser imprimido.
        // pessoas.forEach(IO::println);
        
    }
}
