/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {


    public static void main(String[] args) {
        Contador contador = new Contador();
        contador.atribuir(5);
        System.out.println("Valor atual do contador: " + contador.obterValor());
        contador.incrementar();
        System.out.println("Valor atual do contador: " + contador.obterValor());
    }
}
