/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
//    public String getGreeting() {
//       return "Hello World!";
//    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
        String nome = IO.readln("Entre com seu nome: ");
        IO.println("Olá " + nome);

        int contador = 0;
        for(String valor : args){
            if(valor.equals("POO")){
                System.out.println("Acertou!");
            }else {
                contador ++;
            }
        }
        System.out.println("Total de argumentos diferentes de POO: " + contador);
    }
}
