/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        ArrayList<Pessoa> pessoas = new ArrayList<>();
        HashMap<Integer, Pessoa> pessoaHashMap = new HashMap<>();

        pessoas.add(new Pessoa("Luciano Simas Junior", "luciano.sj@aluno.ifsc.edu.br"));
        pessoas.add(new Pessoa("Pedro Gonçalves", "pedro.gl@aluno.ifsc.edu.br"));
        pessoas.add(new Pessoa("Lionel Messi", "messi@aluno.ifsc.edu.br"));
        pessoas.add(new Pessoa("Luciano Simas Junior", "luciano.sj@aluno.ifsc.edu.br"));
        pessoas.add(new Pessoa("Juca", "juca@example.com"));
        pessoas.add(new Pessoa("Juca", "juca@example.com"));
        pessoas.add(new Pessoa("Juca", "juca@example.com"));

        System.out.println("Listagem das Pessoas Salvas no ArrayList com Lambda");
        pessoas.forEach(x -> System.out.println(x.getNome()));

        pessoaHashMap.put(1, pessoas.get(0));
        pessoaHashMap.put(2, pessoas.get(1));
        pessoaHashMap.put(3, pessoas.get(2));
        pessoaHashMap.put(4, pessoas.get(3));
        pessoaHashMap.put(5, pessoas.get(4));
        pessoaHashMap.put(6, pessoas.get(5));

        // Removendo todas as pessoas com o nome JUCA do hashmap
        pessoaHashMap.values().removeIf(pessoa-> pessoa.getNome().equals("Juca"));

        pessoaHashMap.forEach((Integer, Pessoa)-> System.out.println(Integer + "º " + Pessoa.getNome()));
    }
}
