/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Batedeira batedeira1 = new Batedeira(Cores.AMARELA, Voltagem.V220);
        Batedeira batedeira2 = new Batedeira(Cores.AZUL, Voltagem.V110);

        batedeira1.toString();
        batedeira1.colocarGancho(TipoDeGancho.REFORCADO);
        batedeira1.ligar();
        batedeira1.definirVelocidade(20);
        batedeira1.toString();

        // Simulando erros
        System.out.println(batedeira2.toString());
        batedeira2.toString();
        batedeira2.ligar();
        batedeira2.colocarGancho(TipoDeGancho.RIGIDO);
        batedeira2.toString();
    }
}
