/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args){
        Telefone teste = new Telefone("48991670093");
        System.out.println(teste.toString());
        Email eTeste = new Email("luciano.simasjr@gmail.com");
        System.out.println(eTeste.toString());
    }
}
