/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

        Retangulo retangulo = new Retangulo(5, 6, "ascii");
        System.out.println("Área do retângulo: " + retangulo.getArea());
        System.out.println("Perimetro do retângulo: " + retangulo.getPerimetro());
        System.out.println(retangulo.toString());
    }
}
