/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.ArrayList;
import java.util.Scanner;

public class App {
    private Scanner leia = new Scanner(System.in);
    private ArrayList<Pessoa> pessoas = new ArrayList<>();

    public static void main(String[] args) {
        App app = new App();
        app.menu();
    }

    private void menu(){
        String mensagem =
                """
                \n\tSistema de Cadastro - Menu
                1 - Cadastrar
                2 - Listar todas as pessoas
                3 - Imprimir dados de uma pessoa (invocar toString)
                4 - Sair 
                """;
        while (true){
            System.out.println(mensagem);
            int opcao = this.leia.nextInt();
            switch (opcao){
                case 1:
                    pessoas.add(cadastrar());
                    break;
                case 2:
                    listar();
                    break;
                case 3:
                    System.out.println("Qual é o ID da pessoa que você deseja imprimir?");
                    imprimirDados(leia.nextInt());
                    break;
                case 4:
                    break;
                default:
                    System.out.println("Opção inválida, tente novamente!");
            }
            if(opcao == 4){
                break;
            }
        }
        System.out.println("Programa finalizado...");
    }

    private Pessoa cadastrar(){
        Scanner leia = new Scanner(System.in);
        System.out.println("Qual é o nome da pessoa que deseja cadastrar?");
        String nome = leia.nextLine();
        System.out.println("Qual é o email da pessoa que deseja cadastrar?");
        String email = leia.nextLine();
        Pessoa pessoa = new Pessoa(nome, email);
        System.out.println("Pessoa cadastrada com sucesso!");
        return pessoa;
    }

    private void listar(){
        String linha = "-".repeat(51);
        System.out.println(linha);
        for(Pessoa pessoa : this.pessoas){
            String tabela = String.format("| %05d | %5s | %5s |" , pessoa.getId(), pessoa.getNome(), pessoa.getEmail());
            System.out.println(tabela);
        }
        System.out.println(linha);
    }

    private void imprimirDados(int id){
        System.out.println(this.pessoas.get((id-1)));
    }

}
