/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Horario horario1 = new Horario();
        System.out.println(horario1.toString());
        horario1.setHora(10);
        horario1.setMinutos(32);
        horario1.setSegundos(15);
        Horario horario2 = new Horario(23, 59, 59);
        System.out.println(horario2.toString());
        System.out.println(horario2.horarioPorExtenso());
        System.out.println("Horário convertido em segundos: " + horario2.paraSegundos());
        System.out.println(horario2.diferencaEntreDoisHorarios(horario1));
    }
}
